name: Test FastAPI App

on:
  push:
    branches:
      - main
      - mainX

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Check Python Environment
        run: |
          echo "Python Version:"
          python --version
          echo "Pip Version:"
          pip --version
          echo "Installed Packages:"
          pip list

      - name: Debugging - Print Working Directory and List Files
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in the Directory:"
          ls -la

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies from requirements.txt
        run: pip install --no-cache-dir -r requirements.txt

      - name: List installed packages
        run: pip list  # List installed packages for debugging

      - name: Run tests
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fastapi-app:latest
